### ISSUE TITLE
noise data

### ISSUE THREAD

**Issue by MrMyxzptlk** [abhinandanarya06/OCR#1]
Can you please provide the entire noise dataset?

**Comment by abhinandanarya06** [comment]
The dataset is included with this repo. You can find that in
 https://github.com/abhinandanarya06/OCR/tree/master/data/noise

The data is collected from me from scratch😅 but the project needs more data and improvement in model architecture for tackling the issue found. 

Hope you have an idea. I incourage you to read github wiki and the contribute in this projects.
For further contact, a.arya61200@gmail.com
Have a nice day😇
